name: Tests

on: [push, pull_request]

jobs:
  Luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Luacheck
        uses: lunarmodules/luacheck@v1
